#!/bin/bash

INTERFACE_NAME="enp0s31f6"

if [ "$#" -eq 2 ]
then
  SERVER_ADDR="$2";
  CLIENT_ADDR="$1"
else
  if [ "$#" -eq 0 ]
  then
    SERVER_ADDR="$(arp -a | grep -i 'rail' | grep $INTERFACE_NAME | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')";
    CLIENT_ADDR="$(ifconfig $INTERFACE_NAME | grep 'inet ' | awk '{print $2}')"
  else
    echo "Usage:
      gzsetup
      gzsetup [client IP] [server IP]";
  fi
fi

if [ -z "$SERVER_ADDR" ] || [ -z "$CLIENT_ADDR" ]
then
  if [ -z "$SERVER_ADDR" ]
  then
    echo -e "\e[31mError: no server address\e[0m"
  else
    echo -e "\e[31mError: no client address\e[0m"
  fi
else
  export ROS_IP="$CLIENT_ADDR"
  export ROS_MASTER_URI="http://$CLIENT_ADDR:11311"
  export GAZEBO_MASTER_URI="http://$SERVER_ADDR:11345"
  echo "Done"
fi
