#!/bin/bash

INTERFACE_NAME="enp0s31f6"

if [ "$#" -eq 2 ]
then
  SERVER_ADDR="$2";
  CLIENT_ADDR="$1"
else
  if [ "$#" -eq 0 ]
  then
    SERVER_ADDR="$(arp -a | grep -i 'rail' | awk '{print $2}' | sed 's/^.\(.*\).$/\1/')";
    CLIENT_ADDR="$(ifconfig $INTERFACE_NAME | grep 'inet ' | awk '{print $2}')"
  else
    echo "Usage:
      gzsetup
      gzsetup [client IP] [server IP]";
    exit 1
  fi
fi

export ROS_IP="$CLIENT_ADDR"
export ROS_MASTER_URI="http://$CLIENT_ADDR:11311"
export GAZEBO_MASTER_URI="http://$SERVER_ADDR:11345"
