obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.3, 0.25], [-0.3, 0.25], [-0.3, 0.25], [-0.3, -0.25]]
#robot_radius: ir_of_robot
# inflation_radius: 0.55

map_topic: map
subscribe_to_update: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /stevie/scan_multi, marking: true, clearing: true}

global_frame: map
global_base_frame: base_link
