<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find stevie_description)/urdf/head/head.transmission.xacro" />

	<xacro:include filename="$(find stevie_description)/urdf/head/neck.xacro" />

	<!-- DECLARE VARIABLES -->
	<xacro:property name="head_mass" value="1.5"/>
	<xacro:property name="head_length" value="0.241447327"/>
	<xacro:property name="head_width" value="0.241648773"/>
	<xacro:property name="head_height" value="0.300608185"/>

	<xacro:property name="PI" value="3.14159"/>

	<xacro:macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
              iyy="${m*(x*x+z*z)/12}" iyz="0"
              izz="${m*(x*x+z*z)/12}"
    />
  </xacro:macro>

	<!--************************        HEAD          ************************-->
  <xacro:macro name="head" params="parent" >

		<!-- neck -->
	  <xacro:neck parent="${parent}"/>

		<!-- head link -->
		<link name="head_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/head_collision.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
					<geometry>
				 		<mesh filename="package://stevie_description/meshes/visual/head.STL" scale="0.001 0.001 0.001"/>
					</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 ${head_height / 2}" rpy="0 0 0"/>
				<mass value="${head_mass}"/>
				<xacro:box_inertia m="${head_mass}" x="${head_width}" y="${head_height}" z="${head_length}"/>
			</inertial>
		</link>

		<gazebo reference="head_link">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<maxVel value="0"/>
			<material>Gazebo/White</material>
		</gazebo>

		<!-- neck-head joint -->
		<joint name="neck_head_joint" type="revolute">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
			<limit lower="-${PI/4}" upper="${PI/4}" effort="1000.0" velocity="0.5"/>
			<parent link="neck_link"/>
			<child link="head_link"/>
      <joint_properties damping="10" friciton="0.5"/>
		</joint>

		<!-- transmission -->
		<xacro:head_transmission/>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
