<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find stevie_description)/urdf/head/head.transmission.xacro" />

	<xacro:include filename="$(find stevie_description)/urdf/head/neck.xacro" />

	<!-- DECLARE VARIABLES -->
	<xacro:property name="head_mass" value="1.5"/>
	<xacro:property name="head_length" value="0.241447327"/>
	<xacro:property name="head_width" value="0.241648773"/>
	<xacro:property name="head_height" value="0.300608185"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        HEAD          ************************-->
  <xacro:macro name="head" params="parent" >

		<!-- neck -->
	  <xacro:neck parent="${parent}"/>

		<!-- head link -->
		<link name="head_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/head_collision.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
					<geometry>
				 		<mesh filename="package://stevie_description/meshes/visual/head.stl" scale="0.001 0.001 0.001"/>
					</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 ${head_height / 2}" rpy="0 0 0"/>
				<mass value="${head_mass}"/>
				<xacro:box_inertia m="${head_mass}" x="${head_width}" y="${head_height}" z="${head_length}"/>
			</inertial>
		</link>

		<gazebo reference="head_link">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<maxVel>0</maxVel>
			<material>Gazebo/White</material>
		</gazebo>

		<!-- neck-head joint -->
		<joint name="neck_head_joint" type="revolute">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
			<limit lower="-${PI/4}" upper="${PI/4}" effort="1000.0" velocity="0.5"/>
			<parent link="neck_link"/>
			<child link="head_link"/>
      <dynamics damping="10" friction="0.5"/>
		</joint>

		<!-- transmission -->
		<xacro:head_transmission/>

		<!--************************        SCREENS          ************************-->
		<!-- upper screen link -->
		<link name="upper_screen_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/visual/upper_screen.stl" scale="0.001001 0.001001 0.001001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<mass value="0.00001"/>
				<inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
			</inertial>
		</link>

		<gazebo reference="upper_screen_link">
			<material>Gazebo/Black</material>
		</gazebo>

		<!-- upper_screen joint -->
		<joint name="upper_screen_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="head_link"/>
			<child link="upper_screen_link"/>
		</joint>

		<!-- lower screen link -->
		<link name="lower_screen_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/visual/lower_screen.stl" scale="0.001001 0.001001 0.001001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<mass value="0.00001"/>
				<inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
			</inertial>
		</link>

		<gazebo reference="lower_screen_link">
			<material>Gazebo/Black</material>
		</gazebo>

		<!-- lower_screen joint -->
		<joint name="lower_screen_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="head_link"/>
			<child link="lower_screen_link"/>
		</joint>

		<!--************************        EARCOVERS          ************************-->
		<!-- earcovers link -->
		<link name="earcovers_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/visual/earcovers.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<mass value="0.00001"/>
				<inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
			</inertial>
		</link>

		<gazebo reference="earcovers_link">
			<material>Gazebo/Yellow</material>
		</gazebo>

		<!-- upper_screen joint -->
		<joint name="earcovers_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="head_link"/>
			<child link="earcovers_link"/>
		</joint>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
