<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

<!--
	<xacro:include filename="$(find stevie_description)/urdf/hip/hip.transmission.xacro" />
-->

	<!-- DECLARE VARIABLES -->
	<xacro:property name="neck_mass" value="0.5"/>
	<xacro:property name="neck_volume" value="0.00073"/>
	<xacro:property name="neck_length" value="0.110"/>
	<xacro:property name="neck_width" value="0.110"/>
	<xacro:property name="neck_height" value="0.220"/>

	<xacro:property name="neck_center_of_mass" value="0 0 -0.095837"/>

	<!--Adjust the world's Z axis-->
	<xacro:property name="neck_z_adjustment" value="0.04"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        NECK          ************************-->
  <xacro:macro name="neck" params="parent" >

		<!-- neck link -->
		<link name="neck_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/neck_collision.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
					<geometry>
				 		<mesh filename="package://stevie_description/meshes/visual/neck.STL" scale="0.001 0.001 0.001"/>
					</geometry>
			</visual>
			<inertial>
				<origin xyz="${neck_center_of_mass}" rpy="0 0 0"/>
				<mass value="${neck_mass}"/>
				<xacro:scale_inertia m="${neck_mass}" v="${neck_volume}" ixx="0.000019307" ixy="0.000000" ixz="0.000000" iyy="0.0000019296" iyz="0.000000" izz="0.0000006191"/>
			</inertial>
		</link>

		<gazebo reference="neck_link">
			<material>Gazebo/White</material>
		</gazebo>

		<!-- upper_body-neck joint -->
		<joint name="upper_body_neck_joint" type="revolute">
			<origin xyz="0 0 ${upper_body_height + neck_z_adjustment}" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
			<limit lower="-${PI/4}" upper="${PI/4}" effort="1000.0" velocity="0.5"/>
			<parent link="${parent}"/>
			<child link="neck_link"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="10" friciton="0.5"/>
		</joint>

		<!-- transmission -->
		<xacro:neck_transmission/>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
