<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--
	<xacro:include filename="$(find stevie_description)/urdf/hip/hip.transmission.xacro" />
-->

	<!-- DECLARE VARIABLES -->
	<xacro:property name="neck_mass" value="0.5"/>
	<xacro:property name="neck_length" value="0.110"/>
	<xacro:property name="neck_width" value="0.110"/>
	<xacro:property name="neck_height" value="0.220"/>

	<!--Adjust the world's Z axis-->
	<xacro:property name="neck_y_adjustment" value="-0.065"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        NECK          ************************-->
  <xacro:macro name="neck" params="parent" >

		<!-- neck link -->
		<link name="neck_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/neck_collision.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
					<geometry>
				 		<mesh filename="package://stevie_description/meshes/visual/neck.STL" scale="0.001 0.001 0.001"/>
					</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${neck_mass}"/>
				<inertia ixx="1929662464.0000" ixy="0.0" ixz="-1.590871" iyy="619161024.0000" iyz="0.0" izz="1930710144.0000"/>
			</inertial>
		</link>

		<gazebo reference="neck_link">
			<material>Gazebo/White</material>
		</gazebo>

		<!-- upper_body-neck joint -->
		<joint name="upper_body_neck_joint" type="revolute">
			<origin xyz="0 ${upper_body_height + neck_y_adjustment} 0" rpy="0 0 0"/>
			<axis xyz="0 1 0"/>
			<limit lower="-${PI/4}" upper="${PI/4}" effort="1000.0" velocity="0.5"/>
			<parent link="${parent}"/>
			<child link="neck_link"/>
		</joint>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
