<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find stevie_description)/urdf/wheels/wheels.transmission.xacro" />

	<!-- DECLARE VARIABLES -->
	<xacro:property name="wheel_mass" value="1"/>
	<xacro:property name="wheel_radius" value="0.101238"/>
	<xacro:property name="wheel_thickness" value="0.045983"/>
	<xacro:property name="wheel_box_length" value="0.110775482"/>
	<xacro:property name="chassis_length" value="0.303032"/>
	<xacro:property name="chassis_width" value="0.5"/>

	<xacro:property name="PI" value="3.14159"/>

	<xacro:macro name="cylinder_inertia" params="m r h">
	  <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
	    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
	    izz="${m*r*r/2}"
	  />
	</xacro:macro>

	<!--************************        WHEELS          ************************-->
  <xacro:macro name="wheel" params="parent side" >

		<!-- wheel link -->
		<link name="wheel_${side}_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/wheel_collision.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
			 		<mesh filename="package://stevie_description/meshes/visual/wheel.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<mass value="${wheel_mass}"/>
				<xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_thickness}"/>
			</inertial>
		</link>

		<gazebo reference="wheel_${side}_link">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<kp value="10000000.0"/>
      <kd value="1.0"/>
      <fdir1 value="1 0 0"/>
			<maxVel value="0"/>
			<material>Gazebo/Black</material>
		</gazebo>

		<!-- lower_body-wheel joint -->
		<joint name="wheel_${side}_joint" type="continuous">
			<xacro:if value="${side == 'right'}">
				<origin xyz="0 ${- wheel_thickness - chassis_length/2} 0" rpy="0 0 ${PI/2}"/>
				<axis xyz="1 0 0"/>
			</xacro:if>
			<xacro:if value="${side == 'left'}">
				<origin xyz="0 ${wheel_thickness + chassis_length/2} 0" rpy="0 0 ${-PI/2}"/>
				<axis xyz="-1 0 0"/>
			</xacro:if>
			<parent link="${parent}"/>
			<child link="wheel_${side}_link"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friciton="0.5"/>
		</joint>

		<!-- transmission -->
		<xacro:wheel_transmission side="${side}"/>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
