<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find stevie_description)/urdf/wheels/wheels.transmission.xacro" />

	<!-- DECLARE VARIABLES -->
	<xacro:property name="wheel_mass" value="1"/>
	<xacro:property name="wheel_radius" value="0.101238"/>
	<xacro:property name="wheel_thickness" value="0.045983"/>
	<xacro:property name="wheel_box_length" value="0.110775482"/>
	<xacro:property name="chassis_length" value="0.303032"/>
	<xacro:property name="chassis_width" value="0.5"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        WHEELS          ************************-->
  <xacro:macro name="wheel" params="parent side" >

		<!-- wheel link -->
		<link name="wheel_${side}_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<geometry>
			 		<cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/visual/wheel.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<mass value="${wheel_mass}"/>
				<xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_thickness}"/>
			</inertial>
		</link>

		<gazebo reference="wheel_${side}_link">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<kp value="10000000.0"/>
      <kd value="1.0"/>
      <fdir1 value="1 0 0"/>
			<maxVel>0</maxVel>
			<material>Gazebo/Black</material>
		</gazebo>

		<!-- lower_body-wheel joint -->
		<joint name="wheel_${side}_joint" type="continuous">
			<xacro:if value="${side == 'right'}">
				<origin xyz="0 ${-wheel_thickness - chassis_length/2} 0" rpy="0 0 ${PI/2}"/>
				<axis xyz="1 0 0"/>
			</xacro:if>
			<xacro:if value="${side == 'left'}">
				<origin xyz="0 ${wheel_thickness + chassis_length/2} 0" rpy="0 0 ${-PI/2}"/>
				<axis xyz="-1 0 0"/>
			</xacro:if>
			<parent link="${parent}"/>
			<child link="wheel_${side}_link"/>
      <limit effort="100" velocity="100"/>
      <dynamics damping="0.0" friction="0.5"/>
		</joint>

		<!-- transmission -->
		<xacro:wheel_transmission side="${side}"/>

		<!--************************        WHEEL CAPS          ************************-->
		<!-- wheel cap link -->
		<link name="wheel_cap_${side}_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<!-- slightly larger scale so the yellow cap can cover the one already on the wheel mesh -->
					<mesh filename="package://stevie_description/meshes/visual/wheel_cap.stl" scale="0.001001 0.001001 0.001001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
				<mass value="0.00001"/>
				<inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
			</inertial>
		</link>

		<gazebo reference="wheel_cap_${side}_link">
			<material>Gazebo/Yellow</material>
		</gazebo>

		<!-- wheel_cap joint -->
		<joint name="wheel_cap_${side}_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<parent link="wheel_${side}_link"/>
			<child link="wheel_cap_${side}_link"/>
		</joint>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
