<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--
	<xacro:include filename="$(find stevie_description)/urdf/wheel/wheel.transmission.xacro" />
-->

	<!-- DECLARE VARIABLES -->
	<xacro:property name="wheel_mass" value="1"/>
	<xacro:property name="wheel_radius" value="0.10125"/>
	<xacro:property name="wheel_thickness" value="0.04800"/>
	<xacro:property name="wheel_box_length" value="0.110775482"/>
	<xacro:property name="chassis_length" value="0.3032"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        WHEELS          ************************-->
  <xacro:macro name="wheel" params="parent side" >

		<!-- wheel link -->
		<link name="wheel_${side}_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/wheel_collision.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
			 		<mesh filename="package://stevie_description/meshes/visual/wheel.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="${wheel_mass}"/>
				<inertia ixx="7694243840.0000" ixy="21.275770" ixz="47.828678" iyy="4313382912.0000" iyz="65.004593" izz="4313351168.0000"/>
			</inertial>
		</link>

		<gazebo reference="wheel_${side}_link">
			<material>Gazebo/Black</material>
		</gazebo>

		<!-- footprint-wheel joint -->
		<joint name="wheel_${side}_joint" type="continuous">
			<xacro:if value="${side == 'right'}">
				<origin xyz="0 ${- wheel_thickness - chassis_length/2} 0" rpy="0 0 ${PI/2}"/>
			</xacro:if>
			<xacro:if value="${side == 'left'}">
				<origin xyz="0 ${wheel_thickness + chassis_length/2} 0" rpy="0 0 ${-PI/2}"/>
			</xacro:if>
			<parent link="${parent}"/>
			<child link="wheel_${side}_link"/>
			<axis xyz="0 1 0"/>
		</joint>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
