<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

<!--
	<xacro:include filename="$(find stevie_description)/urdf/wheel/wheel.transmission.xacro" />
-->

	<xacro:include filename="$(find stevie_description)/urdf/arms/shoulders.xacro" />

	<!-- DECLARE VARIABLES -->
	<xacro:property name="arm_mass" value="1"/>
	<xacro:property name="arm_volume" value="0.002083"/>
	<xacro:property name="arm_length" value="0.124658905"/>
	<xacro:property name="arm_width" value="0.1100"/>
	<xacro:property name="arm_height" value="0.304997498"/>

	<xacro:property name="arm_sphere_radius" value="0.03"/>

	<xacro:property name="right_arm_center_of_mass" value="-0.001570 -0.001100 -0.074465"/>
	<xacro:property name="left_arm_center_of_mass" value="-0.001570 0.001100 -0.074465"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        ARMS          ************************-->
  <xacro:macro name="arm" params="parent side" >

		<!-- shoulder -->
		<xacro:shoulder parent="${parent}" side="${side}"/>

		<!-- arm link -->
		<link name="arm_${side}_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<!-- <mesh filename="package://stevie_description/meshes/collision/${side}_arm_collision.stl" scale="0.001 0.001 0.001"/> -->
					<mesh filename="$(find stevie_description)/meshes/collision/${side}_arm_collision.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<!-- <mesh filename="package://stevie_description/meshes/visual/${side}_arm.stl" scale="0.001 0.001 0.001"/> -->
					<mesh filename="$(find stevie_description)/meshes/visual/${side}_arm.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<inertial>
				<xacro:if value="${side == 'right'}">
					<origin xyz="${right_arm_center_of_mass}" rpy="0 0 0"/>
					<xacro:scale_inertia m="${arm_mass}" v="${arm_volume}" ixx="0.0000134861" ixy="-0.0000001570" ixz="-0.0000001100" iyy="0.0000140186" iyz="-0.0000000025" izz="0.0000028663"/>
				</xacro:if>
				<xacro:if value="${side == 'left'}">
					<origin xyz="${left_arm_center_of_mass}" rpy="0 0 0"/>
					<xacro:scale_inertia m="${arm_mass}" v="${arm_volume}" ixx="0.0000134861" ixy="0.0000000026" ixz="-0.0000001553" iyy="0.0000140187" iyz="0.0000000025" izz="0.0000028663"/>
				</xacro:if>
				<mass value="${arm_mass}"/>
			</inertial>
		</link>

		<gazebo reference="arm_${side}_link">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<maxVel>0</maxVel>
			<material>Gazebo/White</material>
		</gazebo>

		<!-- shoulder-arm joint -->
		<joint name="shoulder_arm_${side}_joint" type="revolute">
			<xacro:if value="${side == 'right'}">
				<origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
				<limit lower="${-PI/4}" upper="0" effort="1000.0" velocity="0.5"/>
			</xacro:if>
			<xacro:if value="${side == 'left'}">
				<origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
				<limit lower="0" upper="${PI/4}" effort="1000.0" velocity="0.5"/>
			</xacro:if>
			<axis xyz="1 0 0"/>
			<parent link="shoulder_${side}_link"/>
			<child link="arm_${side}_link"/>
      <dynamics damping="10" friction="0.5"/>
		</joint>

		<!-- transmission -->
		<xacro:arm_transmission side="${side}"/>

		<!-- arm sphere link -->
		<link name="arm_sphere_${side}_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<sphere radius="${arm_sphere_radius}"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<sphere radius="${arm_sphere_radius}"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
				<mass value="0.00001"/>
			</inertial>
		</link>

		<gazebo reference="arm_sphere_${side}_link">
			<material>Gazebo/Yellow</material>
		</gazebo>

		<!-- arm_sphere joint -->
		<joint name="arm_sphere_${side}_joint" type="fixed">
			<origin xyz="0 0 ${-arm_height + arm_sphere_radius + 0.02}" rpy="0 0 0"/>
			<parent link="arm_${side}_link"/>
			<child link="arm_sphere_${side}_link"/>
		</joint>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
