<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--
	<xacro:include filename="$(find stevie_description)/urdf/wheel/wheel.transmission.xacro" />
-->

	<!-- DECLARE VARIABLES -->
	<xacro:property name="shoulder_mass" value="1"/>
	<xacro:property name="shoulder_volume" value="0.000678"/>
	<xacro:property name="shoulder_length" value="0.2130"/>
	<xacro:property name="shoulder_width" value="0.115000381"/>
	<xacro:property name="shoulder_height" value="0.1150"/>

	<xacro:property name="shoulder_center_of_mass" value="-0.023361 0 0.002146"/>

	<xacro:property name="shoulder_z_adjustment" value="-0.17"/>
	<xacro:property name="shoulder_y_adjustment" value="0.035"/>

	<xacro:property name="PI" value="3.14159"/>

	<!--************************        SHOULDERS          ************************-->
  <xacro:macro name="shoulder" params="parent side" >

		<!-- shoulder link -->
		<link name="shoulder_${side}_link">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/collision/shoulder_collision.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://stevie_description/meshes/visual/shoulder.STL" scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<inertial>
				<origin xyz="${shoulder_center_of_mass}" rpy="0 0 0"/>
				<mass value="${shoulder_mass}"/>
				<xacro:scale_inertia m="${shoulder_mass}" v="${shoulder_volume}" ixx="0.0000008220" ixy="0.0000000000" ixz="0.0000000144" iyy="0.0000018788" iyz="0.0000000000" izz="0.0000015944"/>
			</inertial>
		</link>

		<gazebo reference="shoulder_${side}_link">
			<material>Gazebo/White</material>
		</gazebo>

		<!-- upper_body-shoulder joint -->
		<joint name="shoulder_${side}_joint" type="revolute">
			<xacro:if value="${side == 'right'}">
				<origin xyz="0 ${-upper_body_length/2 - shoulder_y_adjustment} ${upper_body_height + shoulder_z_adjustment}" rpy="0 0 ${-PI/2}"/>
				<axis xyz="1 0 0"/>
			</xacro:if>
			<xacro:if value="${side == 'left'}">
				<origin xyz="0 ${upper_body_length/2 + shoulder_y_adjustment} ${upper_body_height + shoulder_z_adjustment}" rpy="0 0 ${PI/2}"/>
				<axis xyz="-1 0 0"/>
			</xacro:if>
			<limit lower="-${PI/4}" upper="${PI/4}" effort="1000.0" velocity="0.5"/>
			<parent link="${parent}"/>
			<child link="shoulder_${side}_link"/>
      <joint_properties damping="10" friciton="0.5"/>
		</joint>

	</xacro:macro>
	<!--***********************************************************************-->

</robot>
